"""empty message

Revision ID: c1459f8e5ef0
Revises: e2c86ad35888
Create Date: 2021-04-16 22:22:50.710030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1459f8e5ef0'
down_revision = 'e2c86ad35888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lag_cancel', sa.Integer(), nullable=False),
    sa.Column('short_hop', sa.Integer(), nullable=False),
    sa.Column('fast_fall', sa.Integer(), nullable=False),
    sa.Column('wavedash', sa.Integer(), nullable=False),
    sa.Column('dash_dance', sa.Integer(), nullable=False),
    sa.Column('teching', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=False))
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_column('user', 'username')
    op.drop_table('progress')
    # ### end Alembic commands ###
